[project]
name = "v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=1.0.2",
    "langgraph-checkpoint-sqlite>=3.0.0",
    "praw>=7.8.1",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "llm",
    "tts",
]

[project.scripts]
scrape-reddit = "services.reddit_scraper:run"

[tool.uv]
package = true

[tool.uv.sources]
llm = { path = "../../llm", editable = true }
tts = { path = "../../tts", editable = true }
